package com.epam.hotel.web.command;

public enum CommandName {
    LOGIN, LOGOUT, REGISTER, ROOM_LIST, SEARCH_RESULT, SEARCH_RESULT_PAGE, INDEX_PAGE, REGISTER_PAGE, CHANGE_LOCALE,
    LOGIN_PAGE, ROOM_INFO, PROFILE, BOOK, ORDER_DETAILS, CONTROL, UPDATE_ORDER_STATUS, SEARCH_USER_BY_ORDER,
    CHANGE_ORDER, CHANGE_ORDER_RESULT, CHANGE_ORDER_RESULT_PAGE, EDIT_BOOK;
}
