package com.epam.hotel.web.command;

/**
 * This class contains the names of the commands.
 *
 * @author Artsem Lashuk
 */
public enum CommandName {
    LOGIN, LOGOUT, REGISTER, ROOM_LIST, SEARCH_RESULT, SEARCH_RESULT_PAGE, INDEX_PAGE, REGISTER_PAGE, CHANGE_LOCALE,
    LOGIN_PAGE, ROOM_INFO, PROFILE, BOOK, ORDER_DETAILS, CONTROL, UPDATE_ORDER_STATUS, SEARCH_USER_BY_ORDER,
    CHANGE_ORDER, CHANGE_ORDER_RESULT, CHANGE_ORDER_RESULT_PAGE, EDIT_BOOK, SEARCH_ORDER_BY_NAME,
    SEARCH_ORDER_BY_PHONE, REVIEWS_PAGE, LEAVE_REVIEW, SEARCH_USER_BY_ID, SUCCESS_REVIEW_PAGE,
    REVIEW_MODERATION, UPDATE_REVIEW_STATUS, CHANGE_ORDER_CONGRATS_PAGE, ABOUT_PAGE;
}
